### ISSUE TITLE
client tests are broken after updating meteor to v2.3

### ISSUE THREAD

**Issue by liitfr** [Meteor-Community-Packages/meteor-browser-tests#36]
```
[[[[[ Tests ]]]]]

=> Started proxy.
=> Started HMR server.
=> Started MongoDB.
I20210630-11:19:41.762(2)? 
I20210630-11:19:41.873(2)? --------------------------------
I20210630-11:19:41.875(2)? ----- RUNNING SERVER TESTS -----
I20210630-11:19:41.876(2)? --------------------------------
I20210630-11:19:41.877(2)? 
I20210630-11:19:41.878(2)? 
I20210630-11:19:41.879(2)? 
I20210630-11:19:41.879(2)?   app
    ✓ package.json has correct name
I20210630-11:19:41.882(2)? 
I20210630-11:19:41.883(2)?   app Server
    ✓ server is not client 
I20210630-11:19:41.885(2)? 
I20210630-11:19:41.886(2)? 
I20210630-11:19:41.886(2)?   2 passing (81ms)
I20210630-11:19:41.887(2)? 
I20210630-11:19:41.888(2)? 
I20210630-11:19:41.888(2)? --------------------------------
I20210630-11:19:41.889(2)? ----- RUNNING CLIENT TESTS -----
I20210630-11:19:41.890(2)? --------------------------------
=> Started your app.

=> App running at: http://localhost:3000/
W20210630-11:19:42.709(2)? (STDERR) /home/mathias/devs2/app/node_modules/selenium-webdriver/lib/promise.js:2626
W20210630-11:19:42.711(2)? (STDERR)         throw error;
W20210630-11:19:42.711(2)? (STDERR)         ^
W20210630-11:19:42.712(2)? (STDERR) 
W20210630-11:19:42.712(2)? (STDERR) WebDriverError: unknown error: Chrome failed to start: exited abnormally.
W20210630-11:19:42.713(2)? (STDERR)   (unknown error: DevToolsActivePort file doesn't exist)
W20210630-11:19:42.713(2)? (STDERR)   (The process started from chrome location /usr/bin/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
W20210630-11:19:42.714(2)? (STDERR)   (Driver info: chromedriver=91.0.4472.101 (af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}),platform=Linux 4.19.104-microsoft-standard x86_64)
W20210630-11:19:42.714(2)? (STDERR)     at Object.checkLegacyResponse (/home/mathias/devs2/app/node_modules/selenium-webdriver/lib/error.js:546:15)
W20210630-11:19:42.715(2)? (STDERR)     at parseHttpResponse (/home/mathias/devs2/app/node_modules/selenium-webdriver/lib/http.js:509:13)
W20210630-11:19:42.715(2)? (STDERR)     at /home/mathias/devs2/app/node_modules/selenium-webdriver/lib/http.js:441:30
W20210630-11:19:42.715(2)? (STDERR)     at /home/mathias/.meteor/packages/promise/.0.12.0.nbwvkk.rgzw++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20210630-11:19:42.716(2)? (STDERR) From: Task: WebDriver.createSession()
W20210630-11:19:42.716(2)? (STDERR)     at Function.createSession (/home/mathias/devs2/app/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
W20210630-11:19:42.717(2)? (STDERR)     at Function.createSession (/home/mathias/devs2/app/node_modules/selenium-webdriver/chrome.js:761:15)
W20210630-11:19:42.717(2)? (STDERR)     at createDriver (/home/mathias/devs2/app/node_modules/selenium-webdriver/index.js:170:33)
W20210630-11:19:42.717(2)? (STDERR)     at Builder.build (/home/mathias/devs2/app/node_modules/selenium-webdriver/index.js:642:16)
W20210630-11:19:42.718(2)? (STDERR)     at startChrome (packages/meteortesting:browser-tests/browser/chromedriver.js:42:93)
W20210630-11:19:42.718(2)? (STDERR)     at startBrowser (packages/meteortesting:browser-tests/server.js:23:7)
W20210630-11:19:42.719(2)? (STDERR)     at clientTests (packages/meteortesting:mocha/server.js:131:3)
W20210630-11:19:42.719(2)? (STDERR)     at packages/meteortesting:mocha/server.js:161:7
W20210630-11:19:42.720(2)? (STDERR)     at packages/meteortesting:mocha/server.js:111:13
W20210630-11:19:42.720(2)? (STDERR)     at done (/home/mathias/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.7fe9hz.khgcd++os+web.browser+web.cordova/npm/node_modules/mocha/lib/mocha.js:497:13)
W20210630-11:19:42.721(2)? (STDERR)     at Runner.<anonymous> (/home/mathias/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.7fe9hz.khgcd++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:804:5)
W20210630-11:19:42.721(2)? (STDERR)     at Runner.emit (events.js:387:35)
W20210630-11:19:42.721(2)? (STDERR)     at Runner.emit (domain.js:470:12)
W20210630-11:19:42.722(2)? (STDERR)     at /home/mathias/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.7fe9hz.khgcd++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:791:12
W20210630-11:19:42.722(2)? (STDERR)     at /home/mathias/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.7fe9hz.khgcd++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:644:9
W20210630-11:19:42.723(2)? (STDERR)     at next (/home/mathias/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.7fe9hz.khgcd++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:284:14)
W20210630-11:19:42.723(2)? (STDERR)     at Immediate.<anonymous> (/home/mathias/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.7fe9hz.khgcd++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:320:5)
W20210630-11:19:42.724(2)? (STDERR)     at processImmediate (internal/timers.js:464:21) {
W20210630-11:19:42.725(2)? (STDERR)   remoteStacktrace: ''
W20210630-11:19:42.725(2)? (STDERR) }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app@0.0.32 test: `TEST_BROWSER_DRIVER=chrome meteor test --production --once --driver-package meteortesting:mocha --settings settings.dev.json`
npm ERR! Exit status 1
npm ERR!
```

**My setup:**

`package.json` : 
```
...
"scripts": {
    ...
    "test": "TEST_BROWSER_DRIVER=chrome meteor test --once --driver-package meteortesting:mocha --settings settings.dev.json",
    "test:app": "TEST_BROWSER_DRIVER=chrome meteor test --full-app --driver-package meteortesting:mocha --settings settings.dev.json",
    "test:watch": "TEST_BROWSER_DRIVER=chrome meteor test --driver-package meteortesting:mocha --settings settings.dev.json",
    "test:app:watch": "TEST_BROWSER_DRIVER=chrome meteor test --full-app --driver-package meteortesting:mocha --settings settings.dev.json",
    ...
}
...
"devDependencies": {
    ...
    "chromedriver": "^91.0.1",
    "selenium-webdriver": "3.6.0",
    ...
}
...
```

I confirm that these tests were working on `2.2` version.

Updated packages during updates are :
```
accounts-base@2.0.0
accounts-facebook@1.3.3
accounts-google@1.4.0
accounts-oauth@1.3.0
accounts-password@2.0.0
accounts-twitter@1.5.0
communitypackages:fast-render@4.0.5
ddp-client@2.5.0
ddp-rate-limiter@1.1.0
ddp-server@2.4.0
dynamic-import@0.7.0
ecmascript@0.15.2
email@2.1.0
facebook-oauth@1.9.0
google-oauth@1.4.0
hot-module-replacement@0.3.0
http@2.0.0
launch-screen@1.3.0
meteor-base@1.5.1
minimongo@1.7.0
mongo@1.12.0
oauth@2.0.0
oauth1@1.4.0
oauth2@1.3.1
promise@0.12.0
server-render@0.4.0
service-configuration@1.1.0
socket-stream-client@0.4.0
twitter-oauth@1.3.0
typescript@4.3.2
webapp@1.11.1
```

removed packages : 
```
pauli:linkedin-oauth@5.0.0
lamhieu:meteorx@2.0.1
npm-bcrypt@0.9.4
splendido:accounts-emails-field@1.2.0
srp@1.1.0
```

new packages : 
```
montiapm:meteorx@2.2.0
```

I have no clue about what is the root cause of this regression, but I would be very glad to help you, as much as I can, to resolve this issue. 
Mathias

**Comment by StorytellerCZ** [comment]
Running at 2.5.1 and getting the following:
```
I20211218-16:48:26.916(1)? --------------------------------
I20211218-16:48:26.916(1)? ----- RUNNING CLIENT TESTS -----
I20211218-16:48:26.916(1)? --------------------------------
W20211218-16:48:26.987(1)? (STDERR) /home/storyteller/.meteor/packages/meteortesting_mocha-core/.8.1.2.yh7gc0.pski++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mocha/lib/runner.js:906
W20211218-16:48:26.988(1)? (STDERR)     throw err;
W20211218-16:48:26.988(1)? (STDERR)     ^
W20211218-16:48:26.988(1)? (STDERR) 
W20211218-16:48:26.988(1)? (STDERR) TypeError: options.toCapabilities is not a function
W20211218-16:48:26.988(1)? (STDERR)     at startChrome (packages/meteortesting:browser-tests/browser/chromedriver.js:54:82)
W20211218-16:48:26.988(1)? (STDERR)     at startBrowser (packages/meteortesting:browser-tests/server.js:27:7)
W20211218-16:48:26.989(1)? (STDERR)     at clientTests (packages/meteortesting:mocha/server.js:140:3)
W20211218-16:48:26.989(1)? (STDERR)     at packages/meteortesting:mocha/server.js:185:7
W20211218-16:48:26.989(1)? (STDERR)     at packages/meteortesting:mocha/server.js:120:13
W20211218-16:48:26.989(1)? (STDERR)     at done (/home/storyteller/.meteor/packages/meteortesting_mocha-core/.8.1.2.yh7gc0.pski++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mocha/lib/mocha.js:1005:7)
W20211218-16:48:26.989(1)? (STDERR)     at Runner.<anonymous> (/home/storyteller/.meteor/packages/meteortesting_mocha-core/.8.1.2.yh7gc0.pski++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mocha/lib/runner.js:1025:5)
W20211218-16:48:26.989(1)? (STDERR)     at Runner.emit (events.js:412:35)
W20211218-16:48:26.989(1)? (STDERR)     at Runner.emit (domain.js:475:12)
W20211218-16:48:26.989(1)? (STDERR)     at /home/storyteller/.meteor/packages/meteortesting_mocha-core/.8.1.2.yh7gc0.pski++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mocha/lib/runner.js:1008:12
W20211218-16:48:26.989(1)? (STDERR)     at /home/storyteller/.meteor/packages/meteortesting_mocha-core/.8.1.2.yh7gc0.pski++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mocha/lib/runner.js:853:7
W20211218-16:48:26.989(1)? (STDERR)     at next (/home/storyteller/.meteor/packages/meteortesting_mocha-core/.8.1.2.yh7gc0.pski++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mocha/lib/runner.js:430:14)
W20211218-16:48:26.990(1)? (STDERR)     at Immediate.<anonymous> (/home/storyteller/.meteor/packages/meteortesting_mocha-core/.8.1.2.yh7gc0.pski++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mocha/lib/runner.js:516:5)
W20211218-16:48:26.990(1)? (STDERR)     at processImmediate (internal/timers.js:464:21)
=> Exited with code: 7
=> Your application is crashing. Waiting for file change.

```
The difference from OP is that my Chrome apparently starts.

**Comment by steven-tailor** [comment]
@StorytellerCZ I've got the same behavior in 2.5.1. Do you have some progress?
`"selenium-webdriver": "^4.1.0"` `"chromedriver": "^96.0.0"`

**Comment by StorytellerCZ** [comment]
I have a reproduction now, so I will work on this as time permits, but any help is appreciated.

**Comment by nachocodoner** [comment]
This was solved in this PR I believe so the issue can be closed, https://github.com/Meteor-Community-Packages/meteor-browser-tests/pull/51
