### ISSUE TITLE
TypeError: chrome.Options.chrome is not a function

### ISSUE THREAD

**Issue by 1u** [Meteor-Community-Packages/meteor-browser-tests#54]
**Describe the bug**
Client tests fail with type error.
both for 1.5.1 and 1.5.3

Unfortunately I can't tell what change caused it (linting error prevented running tests for almost a month)

Repo: https://gitlab.com/Openki/Openki

**Log**

```
I20231118-19:24:55.864(0)?   50 passing (129ms)
I20231118-19:24:55.864(0)? 
I20231118-19:24:55.865(0)? 
I20231118-19:24:55.865(0)? --------------------------------
I20231118-19:24:55.865(0)? ----- RUNNING CLIENT TESTS -----
I20231118-19:24:55.866(0)? --------------------------------
W20231118-19:24:55.883(0)? (STDERR) /root/.meteor/packages/meteortesting_mocha-core/.8.1.2.1pesrr7.nent++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mocha/lib/runner.js:906
W20231118-19:24:55.884(0)? (STDERR)     throw err;
W20231118-19:24:55.885(0)? (STDERR)     ^
W20231118-19:24:55.885(0)? (STDERR) 
W20231118-19:24:55.885(0)? (STDERR) TypeError: chrome.Options.chrome is not a function
W20231118-19:24:55.886(0)? (STDERR)     at startChrome (packages/meteortesting:browser-tests/browser/chromedriver.js:56:89)
W20231118-19:24:55.886(0)? (STDERR)     at startBrowser (packages/meteortesting:browser-tests/server.js:28:7)
W20231118-19:24:55.895(0)? (STDERR)     at clientTests (packages/meteortesting:mocha/server.js:148:3)
W20231118-19:24:55.895(0)? (STDERR)     at packages/meteortesting:mocha/server.js:194:7
W20231118-19:24:55.895(0)? (STDERR)     at packages/meteortesting:mocha/server.js:122:13
```

**Versions**
meteortesting:browser-tests@1.5.1
meteortesting:mocha@2.1.0
meteortesting:mocha-core@8.1.2

see https://gitlab.com/Openki/Openki/-/tree/dev/.meteor?ref_type=heads for all versions.

Any help welcome

**Comment by StorytellerCZ** [comment]
@nachocodoner any initial thoughts on this?

**Comment by nachocodoner** [comment]
@1u which is your selenium-websdriver version?

`chrome.Options.chrome` depends on that package.


In the latest  `meteortesting:browser-tests@1.5.3` version [we reviewed the compatibility on latest `selenium-websdriver` 4.x](https://github.com/Meteor-Community-Packages/meteor-browser-tests/pull/51).

Make sure these npm packages matches the proper versions.

![image](https://github.com/Meteor-Community-Packages/meteor-browser-tests/assets/2581993/e21ab51a-c6dd-4185-bc00-698240602939)

Let me know if this fixed it, otherwise I will take a look into your repo. Thank you!

**Comment by 1u** [comment]
Thx a lot for the quick answer. Version was 3.6.0. 
Didn't had time to test it yet. I'll let you know.
